# A brief review of Python commands


The objective of this file is to overview the basics of Python that you had learned in NE111. These topics are noted at a basic level and you will need to go back to the lecture notes for a more comprehensive review. 

# Preliminaries 

This lecture relies on a prior installation of the [Anaconda distribution](https://www.anaconda.com/products/individual) which will install Python as well as the [Jupyter Notebook](https://jupyter-notebook.readthedocs.io/en/stable/). Jupyter notebook allows us to have cells containing text,

In [ ]:
#as well as cells containing code
#in this case, python code

print("Did you miss Python?")


# How to run python code

There are three methods for you to run python code:

- Running code cells from jupyter notebook. 

- Executing commands directly in a python/ipython shell.

- Creating a py file and running it from the terminal using the command:

    - `run file.py` from ipython.

    - `python file.py` from anaconda prompt.

Try running the following piece of code using all three methods. 

In [ ]:
for i in range(1,10):
    print('*'*(i))

# Basics of Python Programming Language

As an object-oriented programming language, everything in python is an **object** and has a **type**. Let's start by reviewing some data types. 

## Python Data Types 

There are many fundamental data types in python. Values are **dynamically typed**. Here is an incomprehensive list of variable types in python. 

|**Data Type**|**Type in Python**|**Example**|
|------------|--------------|-------------|
|integer     |`int`         |2            |
|float       |`float`       |3.0          |
|string      |`str`         |'hello world'|
|list        |`list`        |['1','2','3']    |
|tuple       |`tuple`       |(1,2,3)      |

The last three types are sequences with list being the only mutable one.

**Note**: An immutable object cannot be changed once defined. 


In [ ]:
# the type of an object can be returned with the type() built-in function

type([2])

## Statements and variables 

Let's review the basic syntax for arithmetic operations. 

|**Symbol**  |**Operator**  |**Example Expression**|**Resulting Value**|
|------------|--------------|----------------------|-------------------|
|-           |negation      |-4                   |-4                |
|+           |addition      |11 + 3.1              |14.1               |
|-           |subtraction   |5 - 19                |-14                |
|*           |multiplication|8.0 * 4               | 32.0              |
|/           |division      |11 / 2                |5.5                |
|//          |integer division: returns the _floor_ of the result of a division |11 // 2|5|
|%           |remainder: returns the remainder from a division|8.5 % 3.5|1.5|
|**           |exponentiation|2 ** 5|32|


In [ ]:
4/3 #the result of this is a float, even when the operands are int

In [ ]:
4//3 #this is an integer division which returns an int by default

In [ ]:
#we can use expressions in the place of operands 
(5-1)//(6/2) #what is the type of the result?

### Variable Names in Python

If we would like to have access to results from certain expressions to be able to utilize them again, we will assign them to a variable. Variable names may not *start with a digit* and **cannot** be a reserved keyword. Using built-in types or functions as variable names will not give an error but should be avoided. 

In [ ]:
#here are a few key words that cannot be used as var names 
#if,and,is,not,while,else,elif


In [ ]:
#let's use appropriate var names for finding the area of a circle

radius_of_circle = 5 #radius of circle (cm)
pi = 3.14
area =  pi * radius_of_circle**2 #area of circle (cm**2)

#what is the var type for the radius?
type(radius_of_circle)

In [ ]:
#How do we see the value for the area

#area #take out the comment here to see this

#we can also use print
print('The area of a circle with a radius of',radius_of_circle,'cms is',area,"cm^2")

## Functions

### Built-in Functions

Python provides many [built-in functions](https://docs.python.org/3/library/functions.html) (in addition to built-in [types](https://docs.python.org/3/library/stdtypes.html) and [constants](https://docs.python.org/3/library/constants.html)). We have already seen one built-in function `print`. Here are some additional built-in functions that will help with converting two of data types we have previously seen. 

|**Function Name**  |**Description**  |
|------------|--------------|
|print()     |Used for printing values.|
|int()       |Convert a number or string to an integer, or return 0 if no arguments are given.  For floating point numbers, this truncates towards zero.      |
|float()     |Convert a string or number to a floating point number, if possible.     |
|str()       |Creates a new string object from the given object.|

In [ ]:
#typing help(name) will bring up any documentation associated with name

#what do you think the type of print is?
#type(print)
#help(print)

print('The area of a circle with radius',float(radius_of_circle),'is',int(area), 'cm^2', sep='\t',end='')


Lets look at some builtin functions that work on collections. 

|**Function Name**  |**Description**  |
|------------|--------------|
|len()       | Return the number of items in a container.|
|max()       | With a single iterable argument, return its biggest item. With two or more arguments, return the largest argument.  |
|min()       |   With a single iterable argument, return its smallest item. With two or more arguments, return the smallest argument. |


In [ ]:
#try finding the number of items in a list
list1=[1,2,3]


#how about the max value?
max_of_list1 = max(list1)
print(max_of_list1)

In [ ]:
#lets try the same task with a tuple 
tuple1=(3,-1,4)

max(tuple1)

In [ ]:
#what about strings? These are collections too!

a_string='Separation of Variables is so much fun!'

print('The length of the string is',len(a_string))


### What are implicit methods in python?

Since everything is an object in python and has a type, there are many builtin methods for each data type that can be used implicitly (as well as explicitly). To see these method use datatype.method . 

In [ ]:
#lets see the available methods for the list type 

list.#press tab to see all the available methods

In [ ]:
#lets try the count method 
#list.count([1,2,3,3,3,4,4,5],4)
[1,2,3,3,3,4,4,5].count(4)

#also index 
#[1,2,3,3,3,4,5].index(3)

In [ ]:
#does it work for strings?
'3B is indeed the height of Engineering at UW'.count('i')

a_string.index('V')

In [ ]:
#what about other methods on strings?
str.split?

a_string.split()

## Practice Exercises

### Exercise 1

Make a list of values. Return the average of the items in the list using the builtin functions `sum` and `len`. Use ? or help(name of function) to get help on each of these methods. 


### Exercise 2

Now using the implicit `insert` method, add the average values to the end of the list. 

## Creating our own Functions

The most general form of the function definition in python is as follows. 

```python
    def myfunction(input_variable1, input_variable2, ...):
        'Documentation string'

        statement1
        statement2
    
        return(output)
```
**Note** that the function header is followed by a colon (:). The body of the function is indented with four spaces. Let us write a function for our circle.

In [ ]:
def area_of_circles(radius):  
    '''
    (float)-> float 
    
    This function returns the area of a circle. 
    
    >>>area_of_circle(2)
    12.56
    >>>area_of_circle(0)
    0.0
    '''
    area_of_circle = 3.14*radius**2
    
    return (radius,area_of_circle)

#using help(my_function) will print any documentation 
#written for user defined functions
#help(area_of_circles)
radius_1=10
(r,area_r)=area_of_circles(radius_1)
#we can use a print statement to show the result
print('The area of a circle with radius',r,'is', area_r)

In [ ]:
#now that we have a function, we can compute the area for many circles easily

#here is a list of radius values 
radii= [2,3,4,5]

#here is an efficient way of constructing a list 
#called a list comprehension 
areas= [area_of_circles(r) for r in radii]  #note how close to human language this syntax is

print('the areas for circles of radii',radii,'are',areas)

## Exercise 3

Combining what we have done before in exercises 1 and 2, we would like to write a function that takes in a list of values, makes a sorted list of these items (look at the `list` methods for this) and adds the average value to the end of the list. The function should retrun this new list. 

In [11]:

def sortAndAverage (listToSort: list[int]) -> list[int]:
    
    sortedList = sorted(listToSort)
    
    average = sum(sortedList) / len(sortedList)
    
    list.insert(sortedList, len(sortedList), average)
    
    return sortedList


unsortedListFloat = [1.1, 2.7, 3.4]

unsortedList  = [2,78,3,1,4,6,8,9,4,344]

print(f"Sorted list + Avg :  {sortAndAverage(unsortedList)}")
    
    
    
    



Sorted list + Avg :  [1, 2, 3, 4, 4, 6, 8, 9, 78, 344, 45.9]


## Loops and Conditions  

Similar to other programming languages, we will need conditional statements in python. Here are some boolean operators in action. 


In [ ]:
sunny = False 

rainy = True

print('The type for sunny is',type(sunny))

if sunny and not rainy:
    print("It must be a beautiful day!")
elif sunny and rainy :
    print("Look out for a rainbow! ")
elif not sunny and rainy:
    print("Clouds are waiting outside...")
else:
    print("Must be nightime!")
    

In [ ]:
##Note there are also == and !=
print(sunny==rainy,sunny!=rainy)
    

Lets look at some loops with examples. A for loop iterates over a collection and sometimes we need to execute a task a certain number of times without having a collection to iterate over. This is when the builtin `range` function becomes useful. 

In [ ]:
#loop over collection

for item in [1,2,3,4]:
    print(item)
    
#lets look at the help for range 
#help(range)

#print a new line
#note strings can be multiplied by a number!
print(30*'-')

#loop with range 
for i in range(5):
    print('the current value of i is',i)

Note that the values in the range sequence correspond (by default) to indices of items in a collection. So if we have a collection thats mutable, this would be a great way to acces (and perhaps change) the values in that collection. 

In [ ]:
#empty list object
list_of_names=[]

#first names
list_of_first_names=['Anny','Nicole','Ben','Lucas']

#last names
list_of_surnames=['Smith','Anderson','Jones','Davidson']

#note that these are parallel list of the same length

#so we can combine the data to make the complete names
for i in range(len(list_of_first_names)):
    
    list_of_names.append(list_of_first_names[i]+' '+list_of_surnames[i])#note that + concatenates two str objects 
    
list_of_names

If we have a condition to work with, a while loop would be more useful. But to make an example more fun, lets try writing a number guessing game using the random number generator from Numpy!

# Modules in python

The ideas of modules in python is very similar to libraries in other programming languages. You have worked with numpy previously. 

Lets import numpy and look at how to make a random integer using one of its functions. 

In [ ]:
#most simple method to import a module 
#syntax : import module_name 
import numpy 

#to access any of the methods inside the module, we will use the dot operator
#example
#help(numpy.random.randint)

#### Now for our guessing game

We will need to ask the user for input so now is a good time to review the `input` function. We will get a random integer from numpy and try to guess it !

In [ ]:
random_number = numpy.random.randint(10) #create random int between 0 and 10 (exclusive)

user_guess = input('guess a number between 0 and 10: ')

while user_guess!=random_number:
    
    user_guess=int(user_guess)  #default type returned from input() is str
    if user_guess <random_number:
        print(f"Your guess of {user_guess} is too low, try again")
        user_guess = input('guess a number between 0 and 10: ')
    elif user_guess > random_number:
        print(f"Your guess of {user_guess} is too high, try again")
        user_guess = input('guess a number between 0 and 10: ')
        
print("You are correct! The answer is ",user_guess)

## Exercise 4

Change the code so that it catches the cases where the user does not provide a number as a guess. 

## Applications of numpy 

We will use numpy in this course extensively so lets spend some time reviewing the basics. In numpy we use the multidimentional array object. We can create arrays a variety of ways.  

In [14]:
import numpy

A=numpy.array([[1,2],[3,4]])#from a list object

#usig one of the initializer methods
B=numpy.ones((2,5)) *5

C=numpy.zeros((4,4))

D=numpy.empty((2,3,2))

print("A=",A,"B=",B,"C=",C,"D=",D,sep='\n')

A=
[[1 2]
 [3 4]]
B=
[[5. 5. 5. 5. 5.]
 [5. 5. 5. 5. 5.]]
C=
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
D=
[[[1.24940830e-311 3.16202013e-322]
  [0.00000000e+000 0.00000000e+000]
  [7.56571287e-307 1.03173043e+166]]

 [[3.35111804e-033 6.11558133e+169]
  [3.92800017e-033 7.96948113e-042]
  [2.00702243e-052 3.83855213e+175]]]


1

The type of an array is ndarray. 

In [ ]:
if type(A)==numpy.ndarray:
    print('This is how to check the type')
elif type(A)==numpy.array:
    print('This is how not to check the type')
    
    

In [ ]:
print(type(B))

A numpy array has many useful attributes. 

In [ ]:
help(numpy.ndarray)

In [ ]:
print("A=",A,"B=",B,"C=",C,"D=",D,sep='\n')
print(A.shape) # shape on an array

print(B.ndim) #number of dimensions

print(C.size) #can you tell me what this is?

print(D.dtype)

Indexing into multidimensional arrays is similar to lists. 
```
startindex:stopindex:increment
```
If any of these are omitted, they are given default values. At least one index should be given. 

In [15]:
A=numpy.arange(100).reshape(2,2,25)

print("A=",A,sep='\n')

print(A[0])#first item in A, which is of shape (2,25)

A=
[[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22
   23 24]
  [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
   48 49]]

 [[50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71 72
   73 74]
  [75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95 96 97
   98 99]]]
[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
  24]
 [25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48
  49]]


In [ ]:
#guess what each of the following would print before execution

In [ ]:
print(A[0,0,0])#A is 3 dimensional so needs three indices to access items

In [ ]:
print(A[0,1,0])

In [ ]:
A=numpy.arange(25).reshape(5,5)

print("A=",A,sep='\n')


In [ ]:
print(A[::,::])#all rows all col

In [ ]:
print(A[0:5:1,0:5:1])#all rows all col

In [ ]:
print(A[::2,::])

In [ ]:
print(A[:4,0:4])#increment can be omitted

All arithmetic operations are elementwise on arrays. With multidimensional arrays you have to be careful with "broadcasting". 

In [ ]:
A=numpy.arange(100).reshape(2,2,25)
B=numpy.arange(50).reshape(2,25)
C=numpy.arange(100).reshape(25,2,2)
D=numpy.arange(25)

In [ ]:
A+B #this is fine,try the next ones

In [ ]:
A+C

In [ ]:
A+D

If you would like to use implement matrix multiplication, use the `@` operator. Make sure the shapes conform. 

In [ ]:
B=numpy.arange(50).reshape(2,25)
E=numpy.arange(50).reshape(25,2)

B@E

#E@B

Lastly, we can use the linear algebra submodule of numpy. 

In [ ]:
numpy.linalg.det(A)#rules of linalg apply

In [ ]:
A=numpy.arange(25).reshape(5,5)
numpy.linalg.inv(A)

## Exercise 5

Write a function that takes in a 2d array as an input. If it is square, display a message to the user “the array is a square matrix” and evaluate the determinant to show the user with a print statement. If the matrix is not square, display the message : “The matrix is — by — and the determinant cannot be evaluated” with the blanks being the row and column of that array. Name this function IsItSquare.py. 


In [23]:
def IsItSquare(A):
    '''
    (ndarray)-> None 
    >>>IsItSquare([[1,2,3],[4,5,6]]) 
    The function needs an array as input
    >>>IsItSquare(np.array([[1,2,3],[4,5,6]])) 
    The matrix is 2 by 3 and the determinant cannot be evaluated. 
    >>>IsItSquare(np.arange(1,10).reshape(3,3)) 
    The array is a square matrix with the det=-9.51619735392994e-16
    '''
    
    if (type(A) != numpy.ndarray):
        print("The function needs an array as input")
        return None
    
    shapeOfA = numpy.shape(A)
    
    if len(shapeOfA) != 2:
        print("Array is not 2 Dimensions")
        return None
    
    if (shapeOfA[0] != shapeOfA[1]):
        print(f"The Matrix is {shapeOfA[0]} by {shapeOfA[1]} and the determinant cannot be evaluated")
        return None
    
    print(f"The Array is a Square Matrix with the det={numpy.linalg.det(A)}")
    
    
IsItSquare([[1,2,3],[4,5,6]]) 
IsItSquare(numpy.array([[1,2,3],[4,5,6]])) 
IsItSquare(numpy.arange(1,10).reshape(3,3)) 

The function needs an array as input
The Matrix is 2 by 3 and the determinant cannot be evaluated
The Array is a Square Matrix with the det=0.0


## Plotting a Function (using [Matplotlib](https://matplotlib.org/))

Let's define a function to find the roots of a quadratic function $ f(x) = ax^2+bx+c $ and plot both the function and the roots.

## Exercise 6


In [28]:
#complete this function declaration
def quadratic_root(a ,b ,c):
    
    """
    (float, float, float) -> tuple
    
    Return the roots of a quadratic function f(x) = a x^2 + b x + c with real coefficients.
    
        >>> quadratic_root(-1., 2., 3.)
        (3.0,-1.0)
        >>> quadratic_root(1, 0., -4.)
        (2.0,-2.0)

    """
    delt=(b*b)-4*a*c
    
    x1,x2= ((-b+numpy.sqrt(delt))/(2*a),  (-b-numpy.sqrt(delt))/(2*a))
   
    # using the quadratic formula, compute the two roots of the polynomial
    
    return (x1,x2)

In [29]:
#You can use tuples for multiple assignments
(a, b, c) = (-1., 2., 3.)
(x1, x2) = quadratic_root(a ,b ,c) #make sure to complete the function before running this


print(f'for {a}x^2+{b}x+{c}, the roots are {x1} and {x2}')#using print with the formatted string introduced in python 3.6+

for -1.0x^2+2.0x+3.0, the roots are -1.0 and 3.0


Now that we have determined the two roots for the problem, let us visualize the second order polynomial as well as the two answers to check that they are indeed the roots. 

In [ ]:
#we require the matplotlib library for plotting
#syntax : import module_name as other_name 
import matplotlib.pyplot as plt


# We would like to plot the quadratic 
# lambda allows us to create a small anonymous function in python
f= lambda x:a*x**2+b*x+c

x=numpy.linspace(-2,4,50)#points for plot

#now we can call the methods with the new module name
plt.plot(x,f(x),'b-',label=f'$ {a}x^2+{b}x+{c}$')                             
plt.plot(x,numpy.zeros([len(x),1]),'r--')
plt.plot(x1,f(x1),'ks',markersize=10,markerfacecolor='red',label=f'$(x_1,f(x_1))$ = {(x1,f(x1))}')
plt.plot(x2,f(x2),'go',markersize=13,markerfacecolor='white',label=f'$(x_2,f(x_2))$ = {(x2,f(x2))}')
plt.title('Roots of a quadratic')
plt.legend()
plt.show()


There are two more types of import :

   - from module import something
   - from module import * 
   
Instead of testing these on python modules, run them on your own module as part of the last exercise. 

## Exercise 7

Create your own py files called `quadratic.py`. In this file, include your `quadratic_root` function. Now in a terminal:

1. From this module, import the quadratic_root function and find the roots for $ f(x) = x^2-x-2 $. 
2. Now modify your module such that *only when it is run as a script*, it asks the user for the coefficients a,b and c and displays the roots for the quadratic $ f(x) = ax^2+bx+c $. (hint : you will need the `__name__` variable)
