In [13]:
import numpy as np

AVals = [[3 , -0.1, -0.2], [0.1, 7, -0.3], [0.3, -0.2, 10]]
bVals = [[7.85], [-19.3], [71.4]]
bVals2 = [[7.85, -19.3, 71.4]]

A = np.array(AVals)
b = np.array(bVals2).T

print(A)
print(b)

AugmentMatrix = np.concatenate((A,b), axis = 1)
#AugmentMatrix2 = np.hstack((A, b))

print(AugmentMatrix)
#print(AugmentMatrix2)

solve = np.linalg.solve(A, b)

print(solve)


[[ 3.  -0.1 -0.2]
 [ 0.1  7.  -0.3]
 [ 0.3 -0.2 10. ]]
[[  7.85]
 [-19.3 ]
 [ 71.4 ]]
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
[[  3.    -0.1   -0.2    7.85]
 [  0.1    7.    -0.3  -19.3 ]
 [  0.3   -0.2   10.    71.4 ]]
[[ 3. ]
 [-2.5]
 [ 7. ]]


In [15]:
# LU Decomposition
from scipy.linalg import lu_factor, lu_solve, lu

P, L, U = lu(A)

print("P=", P)
print( "L=", L)
print( "U=", U)

d = np.linalg.solve(L, b)

x_lu = np.linalg.solve(U, d) # this is solution

print(x_lu)

# builtin 
x_lu_builtin = lu_solve(lu_factor(A), b)

print(x_lu_builtin)






P= [[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
L= [[ 1.          0.          0.        ]
 [ 0.03333333  1.          0.        ]
 [ 0.1        -0.02712994  1.        ]]
U= [[ 3.         -0.1        -0.2       ]
 [ 0.          7.00333333 -0.29333333]
 [ 0.          0.         10.01204188]]
[[ 3. ]
 [-2.5]
 [ 7. ]]
[[ 3. ]
 [-2.5]
 [ 7. ]]
